<a href="https://colab.research.google.com/github/sangeunlim/py-12/blob/master/Summary_numpy_py12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

>>[라이브러리-overview](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=W-zP7IysFaau)

>>>[파이썬 코드에서 라이브러리 사용법](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=07PHYQGNFtRW)

>>[라이브러리-numpy](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=72WBxcW0HCyt)

>>>[numpy](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=S-HFCnJqHGrd)

>>>[numpy vs list](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=LsOiN438LzNs)

>>[라이브러리-numpy vector(1차원 배열)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=RezQclzPIhRq)

>>>[벡터(vector)생성](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=cFZCphkZInsc)

>>>[벡터(vector)산술연산](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=hXnETshRMBOE)

>>[라이브러리- numpy matrix(행렬)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=zG12mvheLIFQ)

>>>[행렬(matrix)생성](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=fZtfV2xuLMpB)

>>>[형 변환(reshape)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=LTrYsrxBMw0o)

>>[라이브러리-numpy 행렬 곱(dot product)(1)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=JMmN6jwgNjFI)

>>>[행렬 곱(dot product)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=iip47T-yNqmH)

>>[라이브러리-numpy 행렬 곱(dot product)(2)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=N2SXRf-xPQ0f)

>>>[행렬 곱(dot product)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=U6ReyZXPPZ4R)

>>[라이브러리-numpy broadcast](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=tHcL3gb1Qdfc)

>>[라이브러리-numpy 전치행렬(transpose)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=O5SjyxayRcOi)

>>>[전치행렬(transpose)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=CUwufUUuRsAB)

>>[라이브러리-numpy 행렬 indexing/slicing](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=PopFpNw-Ti9H)

>>>[행렬 원소 접근(1)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=onapnMKwTowo)

>>[라이브러리-numpy 행렬 iterator](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=Y8eZ0E7LWJIX)

>>>[행렬 원소 접근(2)](#updateTitle=true&folderId=1I-mKsst3XRGgBrZkZRWgFh2Gm98rzEj0&scrollTo=bEsChNPTWOqY)



## 라이브러리 - overview
### 라이브러리 설치 
 pip install <라이브러리 이름>

In [0]:
import numpy

A=numpy.array([1,2])

print("A ==",A, ", type ==",type(A))

A == [1 2] , type == <class 'numpy.ndarray'>


In [0]:
import numpy as np

A=np.array([1,2])

print("A ==",A, ", type ==", type(A))

A == [1 2] , type == <class 'numpy.ndarray'>


In [0]:
from numpy import exp

result = exp(1)

print("result ==",result, ", type ==",type(result))

result == 2.718281828459045 , type == <class 'numpy.float64'>


In [0]:
from numpy import *

result = exp(1) + log(1.7) + sqrt(2)

print("result ==",result, ", type ==",type(result))

result == 4.663123641894311 , type == <class 'numpy.float64'>


## 라이브러리 - numpy

### 머신러닝 코드 개발 경우 자주 사용되는 벡터, 행렬 등을 표현하고 연산할 때 반드시 필요



*  숫자, 사람, 동물 등의 인식을 하기 위해서 
이미지데이터를 행렬로 변환하는것이 중요

*   행렬 연산을 위해서는 리스트를 사용할 수도 있지만 
오류가능성이 높기 때문에,  numpy 사용이 필수

In [0]:
import numpy as np

In [0]:
# 리스트로 행렬 표현

A = [[1, 0], [0, 1]]
B = [[1, 1], [1, 1]]

A + B        # 행렬 연산이 아닌 리스트 연산

[[1, 0], [0, 1], [1, 1], [1, 1]]

In [0]:
# numpy matrix, 직관적임

A = np.array([ [1, 0], [0, 1] ])
B = np.array([ [1, 1], [1, 1] ])

A + B     # 행렬 연산

array([[2, 1],
       [1, 2]])

## 라이브러리 - numpy vector(1차원 배열)

### 연산을 위해서 vector, matrix 등의 형상, 차원을 확인하는 것이 필요
=> 벡터는 np.array([⋯])를 사용하여 생성


In [0]:
A=np.array([1,2,3])
B=np.array([4,5,6])

In [0]:
# vector A, B 출력

print("A ==", A, ", B ==", B)

A == [1 2 3] , B == [4 5 6]


In [0]:
# vector A, B 형상 출력 => shape

print("A.shape ==", A.shape, ", B.shape ==", B.shape)

A.shape == (3,) B.shape == (3,)


In [0]:
# vector A, B 차원 출력 => ndim

print("A.ndim ==", A.ndim, ", B.dim ==", B.ndim)

A.ndim == 1 B.ndim == 1


###  벡터 산술연산

 =>  벡터의 각각의 원소에 대해서 행해짐



In [0]:
#vector 산술 연산

print("A + B ==", A+B)
print("A - B ==", A-B)
print("A * B ==", A*B)
print("A / B ==", A/B)

A + B == [5 7 9]
A - B == [-3 -3 -3]
A * B == [ 4 10 18]
A / B == [0.25 0.4  0.5 ]


## 라이브러리 - numpy matrix (행렬)
=> np.array([ [⋯], [⋯], ⋯ ])를 사용하여 생성

In [0]:
A = np.array([ [1, 2, 3], [4, 5, 6] ])
B = np.array([ [-1, -2, -3], [-4, -5, -6] ])

In [0]:
# matrix A, B 형상 출력 => shape

print("A.shape ==", A.shape, ", B.shape ==", B.shape)

A.shape == (2, 3) , B.shape == (2, 3)


In [0]:
# matrix A, B 차원 출력 => ndim

print("A.ndim ==", A.ndim, "B.ndim ==", B.ndim)

A.ndim == 2 B.ndim == 2


### 형 변환 (reshape)
=> 벡터를 행렬로 변경하거나 행렬을 다른 형상의 행렬로 변경하기 위해서는 reshape() 사용하여 행렬의 shape 을 변경

In [0]:
# vector 생성

C = np.array([1, 2, 3])

In [0]:
# vector C 형상 출력 => shape

print("C.shape ==", C.shape)

C.shape == (3,)


In [0]:
# vector를 (1,3) 행렬로 형 변환

C = C.reshape(1, 3)

print("C.shape ==", C.shape)

C.shape == (1, 3)


## 라이브러리 - numpy 행렬 곱(dot product) (1)
### reshape 또는 전치행렬 등을 사용하여 형 변환을 한 후에 행렬 곱 실행해야 함

=> A 행렬과 B 행렬의 행렬 곱은 np.dot(A,B)로 나타냄
A행렬의 열벡터와 B 행렬의 행벡터가 같아야함.

In [0]:
A = np.array([ [1, 2, 3], [4, 5, 6] ])   # 2X3 행렬
B = np.array([ [-1, -2], [-3, -4], [-5, -6] ])   #3X2 행렬

In [0]:
# (2X3) dot product (3X2) == (2X2) 행렬

C = np.dot(A, B)    # 행렬 곱 수행

In [0]:
# matrix A, B 형상 출력 => shape

print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print("C.shape ==", C.shape)
print(C)

A.shape == (2, 3) B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]


## 라이브러리 - numpy 행렬 곱(dot product) (2)
=> 행렬곱 조견을 만족하는 다양한 크기의 행렬을 연속으로 만들고 행렬 곱을 연속으로 계산하면서 결과 값을 만들 수 있기 때문에 머신러닝과 이미지 프로세싱 분야에서 자주 사용됨

## 라이브러리 - numpy broadcast
### numpy 에서는 크기가 다른 두 행렬 간에도 사칙연산을 할 수 있는데 이를 브로드캐스트라고 지칭 => 차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산

In [0]:
A = np.array([ [1, 2], [3, 4] ])
b = 5

print(A+b)

[[6 7]
 [8 9]]


In [0]:
C = np.array([ [1, 2], [3, 4] ])
D = np.array([4, 5])

print(C+D)

[[5 7]
 [7 9]]


## 라이브러리 - numpy 전치행렬 (transpose)

=> 원본 행렬의 열은 행으로, 행은 열로 바꾼것 
원본 행렬을 A 라고하면 전치행렬은 A^T 로 나타냄

In [0]:
A = np.array([ [1, 2], [3, 4], [5, 6] ])   # 3X2 행렬

B = A.T    # A의 전치행렬, 2X3 행렬

In [4]:
print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print(A)
print(B)

A.shape == (3, 2) , B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [0]:
# vector 전치행렬

C = np.array([1, 2, 3, 4, 5])   #vector, matrix 아님
D = C.T           # C는 벡터이므로 transpose 안됨

In [0]:
E = C.reshape(1, 5)    # 1X5 matrix
F = E.T     # E의 전치행렬

In [8]:
print("C.shape ==", C.shape, ", D.shape ==", D.shape)
print("E.shape ==", E.shape, ", F.shape ==", F.shape)
print(F)

C.shape == (5,) , D.shape == (5,)
E.shape == (1, 5) , F.shape == (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


## 라이브러리 - numpy 행렬 indexing / slicing

### 행렬 원소 접근 (1)


*   행렬 원소를 명시적으로 접근하기 위해서는 리스트처럼 인덱싱 / 슬리이싱 사용가능


In [0]:
A = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2)

print("A.shape ==", A.shape)
print(A)

A.shape == (3, 2)
[[10 20]
 [30 40]
 [50 60]]


In [0]:
print("A[0, 0] ==", A[0, 0], ", A[0][0] ==", A[0][0])  # 1행 1열
print("A[2, 1] ==", A[2, 1], ", A[2][1] ==", A[2][1])  # 3행 2열

A[0,0] == 10 A[0][0] == 10
A[2,1] == 60 A[2][1] == 60


In [0]:
print("A[0:-1, 1:2] ==", A[0:-1, 1:2])   # 인덱스 0인 1행부터, -1-1=-2인 2행까지의 모든 데이터
                                         # 인덱스 1인 2열부터 2-1=1인 2열까지의 모든 데이터

A[0:-1, 1:2] == [[20]]


In [0]:
print("A[ :, 0] ==", A[:, 0])   # 모든 행 1열
print("A[ :, :] ==", A[:, :])   # 모든 행, 모든 열

A[:, 0] == [10 30 50]
A[:, :] == [[10 20]
 [30 40]
 [50 60]]


## 라이브러리 - numpy 행렬 iterator
### 행렬 원소 접근(2)
=> 행렬 모든 원소를 access 하는 경우에는 iterator 사용가능


=> C++, Java iterator 처럼 next() 메소드를 통해 데이터 값을 처음부터 끝까지 순차적으로 읽어들이는 방법을 제공

In [0]:
import numpy as np

A = np.array([ [10, 20, 30, 40], [50, 60, 70, 80] ])

In [0]:
print(A, "\n")
print("A.shape ==", A.shape, "\n")

[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 



In [0]:
# 행렬 A의 iterator 생성

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
  
  idx = it.multi_index
  
  print("current value => ", A[idx])
  
  it.iternext()

current value =>  10
current value =>  20
current value =>  30
current value =>  40
current value =>  50
current value =>  60
current value =>  70
current value =>  80
