<a href="https://colab.research.google.com/github/sangeunlim/py-12/blob/master/ann/DL1_Neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[link:DeepLearningFastStart](https://github.com/alfredessa/DeepLearningFastStart/blob/master/DL-Neuron.ipynb)

In [1]:
from IPython.core.display import HTML, Image
css_file = 'style.css'
HTML(open(css_file, 'r').read())

FileNotFoundError: ignored

>[Deep Learning Fast Start](#scrollTo=rpOz6FctZksc)

>>[The Neuron](#scrollTo=rpOz6FctZksc)

>[Neuron: Learning Objectives](#scrollTo=AdYUbt7NZksh)

>[What is a Neuron?](#scrollTo=VyrTxpNgZksr)

>[Neuron Structure](#scrollTo=E7F0cR8wZksv)

>[Neuron's Two Step Computation](#scrollTo=x2OLc0TjZktA)

>[Neuron Computation (Step 1)](#scrollTo=fQXjX_SGZktb)

>[Neuron Computation Example (Step 1)](#scrollTo=QsFRvAmzZktO)

>[Code for Neuron Computation (Step 1): 선형합](#scrollTo=Vz7wIWsvZktq)

>>>[Using For Loop](#scrollTo=DfYosU--Zktr)

>>>[Using List Comprehension](#scrollTo=3CRFr95xZkt9)

>>>[Using Numpy Dot Product](#scrollTo=WbQEmj4RZkuH)

>[Neuron Computation (Step 2): 비선형 활동](#scrollTo=bsM3Lj8kZkuS)

>[Activation Function Examples](#scrollTo=OLNNuCKaZkuX)

>[Computation Example (Step 2)](#scrollTo=lq_CD75oZkuf)

>[Code for Neuron Activation (Step 2)](#scrollTo=UnDed5j5Zkuj)

>>>[스텝 함수 (Heaviside function)](#scrollTo=S8d3xeTXZkuk)

>>>[ReLU 함수 (Rectified Linear Unit function)](#scrollTo=-JvsHNIKZkuq)

>>>[Sigmoid 함수](#scrollTo=0ewW3Bf2Zkuu)

>[Data Structures for Neuron Computation](#scrollTo=dFL_PpKcZku0)

>[Neuron Class](#scrollTo=IrCEDxj0ZkvF)

>>>[Define Activation Functions](#scrollTo=XsuyR0uVZkvM)

>>>[Define Neuron Class](#scrollTo=-6iSXoGXZkvS)

>>>[Create Neuron Object and Compute](#scrollTo=xKkWvT0WZkvX)

>>>[선형합(transfer)](#scrollTo=Cyjcmq68Zkv0)

>>>[Activating neuron](#scrollTo=Ai5ejhUYZkv8)

>>>[뉴런의 기본 활동 윈리가 이해됩니까?](#scrollTo=PIqhE_UaZkwP)

>>>[[도전 과제]  100 개의 입력에 대한 뉴런의 출력을 세 가지 방식으로 구하시오.](#scrollTo=BSoP0vwBZkwR)

>[Great! Welcome to the World of Perceptron.](#scrollTo=LzTllMcCZkw1)



# Deep Learning Fast Start

## The Neuron


<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Deep Learning Fast Start</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://alfredessa.com" property="cc:attributionName" rel="cc:attributionURL">Alfred Essa</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

# 1. Neuron: Learning Objectives

**1:** Understand the basic *concept* of an artificial neuron or perceptron

> [perceptron(퍼셉트론 개념)](http://blog.naver.com/samsjang/220948258166)

**2:** Describe a neuron's two-step *computation* process
> 뉴런은 입력값에 두 단계로 계산을 수행하여서 출력값으로 변환한다.

**3:** Recognize the *parameters* of a neuron
> 뉴런의 파라미터는 가중치(weight)와 바이어스(bias)로 구성된다.

**4:** Understand how a single neuron can implement linear or logistic regression

**5:** Write code, in the form of crude *Python class*, which implements a neuron's computation


# 2.  What is a Neuron?

> **Definition**: A neuron is the *atomic computational unit* of an **artificial neural network** (ANN).

 # 3. Neuron Structure

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/bioneuron.png" style="width: 50%; height: 50%" />

- In a biological neuron input signals come in through dendrites
> dendrites: 가지돌기

- The signals are processed in the nucleus

- The output signal is transmitted to other neurons through the axon
>axon: 축삭돌기

- 생물학적인 뉴런은 덴드라이트들(dendrites)로부터 받은 입력 신호(이온 흐름)를 처리한 후 일정 기준이 만족되면 액손(axon)을 통해 다른 뉴런에게 신호(정보)를 전달한다. 
> McCulloch-Pitts neuron (MCP neuron)

- 생물학적인 뉴런의 정보 처리 구조를 수학적으로 도식화하면 다음과 같다.
> 퍼셉트론(perceptron) 학습 규칙

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/function.png" style="width: 50%; height: 50%" />

- A neuron can be viewed as a mathematical function

- A neuron accepts a set of inputs, performs a computation on that input, and returns an output

- 뉴런은 주위의 다른 뉴런들로부터 여러 입력을 받아 내부(핵)에서 처리한 후 일정 조건이 되면 다른 뉴런에게 처리된 결과를 전송한다. 

# 4. Neuron's Two Step Computation

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/twostep.png" style="width: 60%; height: 60%" />

- A neuron performs its computation in two-steps (뉴런 내에서의 처리는 두 단계로 구성된다.)

- During step 1 a linear function operates on the inputs on the inputs: $x_{1}..x_{n}$ and produces an output $z$. --> 선형 합 (transfer)

- During step 2 a non-linear function, called the activation function, performs a computation on the input $z$ to produce the final output $y$.  --> 비선형 활동(activation)

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/twostep2.png" style="width: 60%; height: 60%" />

- We will represent the first function, sometimes called the transfer function, with the symbol $\Sigma$. -> 선형합(transfer)

- We will represent the second function, called the activation function, with the symbol $\phi$ -> 비선형 활동(activation)

# 5. Neuron Computation (Step 1)

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/transferfunction.png" style="width: 75%; height: 75%">

- Each neuron accepts $n$ inputs.

- A "weight" is associated with each input: $x_{n} \mapsto w_{n}$
> 가중치는 각각의 입력에 할당된다.

- Then a "bias" term $b$ is added to the weighted sum of inputs.
> 가중치가 뱐영된 입력합에 바이어스(상수값)이 더해진다.

# 6. Neuron Computation Example (Step 1)

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/transferexample.png" style="width: 60%; height: 60%" >

- We have three inputs for this neuron, with values: $[2.3,4.5,1.3]$

- A "weight" is associated with each input: $[3.2, -1.9, 2.5]$. We also have a value for the bias: $-1$

- 각 입력값은 가중치(weight)를 곱한 후 합산한 후, 상수값(bias)가 더해져서 처리된다.

- The weighted sum plus the bias is $z = 1.06$

# 7. Code for Neuron Computation (Step 1): 선형합
> 세 가지 방법으로 뉴런을 정의

> 선형합(transfer) 기능 설계

### Using For Loop

In [0]:
inputs = [2.3,4.5,1.3]
weights = [3.2,-1.9,2.5]
bias = -1

In [0]:
def neuron1(x,w,b):
    z=0
    for x_,w_ in zip(x,w):
        z += x_ * w_
    z+=b
    return z

In [4]:
neuron1(inputs,weights,bias)

1.0600000000000005

### Using List Comprehension

In [0]:
def neuron2(x,w,b):
    z = sum([x_*w_ for x_,w_ in zip(x,w)]) + b 
    return z

In [6]:
neuron2(inputs,weights,bias)

1.0600000000000005

### Using Numpy Dot Product

In [0]:
import numpy as np
def neuron3(x,w,b):
    z = np.dot(w,x) + b
    return z

In [8]:
neuron3(inputs,weights,bias)

1.0600000000000005

# 8. Neuron Computation (Step 2): 비선형 활동

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/twostep2.png" style="width: 60%; height: 60%">|

# 9. Activation Function Examples 

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/stepfunction.png" style="width: 60%; height: 60%">|

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/relufunction.png" style="width: 60%; height: 60%">|

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/sigmoidfunction.png" style="width: 60%; height: 60%">

# Computation Example (Step 2)

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/activationexample.png" style="width: 60%; height: 60%">

# Code for Neuron Activation (Step 2)
> 세 가지 함수로 뉴런의 활동을 정의

### 스텝 함수 (Heaviside function)
> 0 or 1

In [0]:
def heaviside(z):
    if z<0:
        return 0
    else:
        return 1
#     return np.heaviside(z, 0)  # threshold = 0

### ReLU 함수 (Rectified Linear Unit function)
> 0 or positive number

In [0]:
def relu(z):
    return np.maximum(0,z)

### Sigmoid 함수

> $-\infty \lt z \lt \infty$ 범위를 0 ~ 1 범위로 근사.

In [0]:
def sigmoid(z):
        return 1.0/(1.0+np.exp(-z))

<img src="https://t1.daumcdn.net/cfile/tistory/275BAD4F577B669920" style="width: 60%; height: 60%">

> https://t1.daumcdn.net/cfile/tistory/275BAD4F577B669920

***

# 10. Data Structures for Neuron Computation

- We represent the input $\mathbf{x}$ as a column vector. $\mathbf{x} =\begin{bmatrix}
    x_1\\
    x_2\\
    \vdots \\
    x_n
\end{bmatrix}$

- We represent the weights $\mathbf{w}$ as a column vector but take it's transform to obtain a row vector $\mathbf{w}^\top = \begin{bmatrix}
    w_1\
    w_2\
    \dots \
    w_n
    \end{bmatrix}$

- We represent the bias $\mathbf{b}$ as a scalar $b$.

- The result of the transfer function computation:  $z = \mathbf{w}^\top \mathbf{x} + b$

- The result of the activation function computation: $a$ = $\phi(z)$

$$ z = \begin{bmatrix}
    x_1\\
    x_2\\
    \vdots \\
    x_n
\end{bmatrix} 
\begin{bmatrix}
    w_1\
    w_2\
    \dots \
    w_n
    \end{bmatrix} + b$$

$$z = \mathbf{w}^\top \mathbf{x} + b$$

# 11. Neuron Class 

In [0]:
import numpy as np

### Define Activation Functions

In [0]:
def relu(z):
    return np.maximum(0,z)

def sigmoid(z):
    return 1.0/(1.0+np.exp(-z))
    
def heaviside(z):
#     if z<0:
#         return 0
#     else:
#         return 1
    return np.heaviside(z,0) # threshold = 0

### Define Neuron Class

In [0]:
class Neuron(object):
    
    # size = size or number of inputs
    def __init__(self,size):
        self.weights = np.random.randn(size)
        self.bias = np.random.randn()
        
    # computes z = weighted sum + bias
    def y_hat(self,x,phi):
        z = np.dot(self.weights,x) + self.bias  # transfer
        a = phi(z) # activation
        return(a)  # output
    
    
    # updates weights and biases
    def update_params(self,weights,bias):
        self.weights = np.array([weights])
        self.bias = np.array([bias])

### Create Neuron Object and Compute

In [0]:
# Set a seed for random number generation
np.random.seed(0)

In [16]:
N1 = Neuron(3)  # input size = 3
N1

In [17]:
N1.weights,N1.bias

(array([1.76405235, 0.40015721, 0.97873798]), 2.240893199201458)



---



### Neuron 
> Make another neuron with different parameters

In [0]:
# Set new weights and bias
# Make another neuron with different parameters
weights = [3.2,-1.9,2.5]
bias = -1

In [0]:
N1.update_params(weights,bias)

In [20]:
N1.weights,N1.bias

(array([[ 3.2, -1.9,  2.5]]), array([-1]))

### 선형합(transfer)

In [0]:
# input
x = [2.3,4.5,1.3]  # 입력

In [22]:
np.dot(N1.weights,x) + N1.bias

array([1.06])

### Activating neuron

In [23]:
N1.y_hat(x,heaviside)

array([1.])

In [24]:
N1.y_hat(x,relu)

array([1.06])

In [25]:
N1.y_hat(x,sigmoid)

array([0.74269055])

### 뉴런의 기본 활동 윈리가 이해됩니까?

***

### [도전 과제]  100 개의 입력에 대한 뉴런의 출력을 세 가지 방식으로 구하시오.

> 세 가지 활동 함수 이용 : heaviside(), relu(), sigmoid()

In [0]:
# Set a seed for random number generation
np.random.seed(0)

In [0]:
N100 = Neuron(100)

In [28]:
N100.weights,N100.bias

(array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
         0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
         0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574,
        -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462,
        -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877,
         0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215,
         0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275,
        -1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
        -0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028,
        -0.89546656,  0.3869025 , -0.51080514, -1.18063218, -0.02818223,
         0.42833187,  0.06651722,  0.3024719 , -0.63432209, -0.36274117,
        -0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614,
        -0.40178094, -1.63019835,  0.46278226, -0.9

In [0]:
# input(입력)
x100 = np.random.randn(100)
# x100.shape

In [30]:
# transfer: weighted linear sum + bias
np.dot(N100.weights,x100) + N100.bias

10.886612705858221

In [31]:
N100.y_hat(x100,heaviside)

1.0

In [32]:
N100.y_hat(x100,relu)

10.886612705858221

In [33]:
N100.y_hat(x100,sigmoid)

0.9999812933486968

***

# Great! Welcome to the World of Perceptron.